-- Generated by `morpholog generate views` - do not edit.
-- programme: glasshouse
-- model hash: sha256:7045468e03712a8bdaf66e6f2d43337bbf9b88c0803c6bbb34f597735fcc3897

BEGIN;

CREATE SCHEMA IF NOT EXISTS "morpholog_views";

-- View for base predicate `MayCaptureTrade`.
CREATE OR REPLACE VIEW "morpholog_views"."may_capture_trade" AS
WITH governed_claims AS (
    SELECT arguments, asserted_in, asserted_at
    FROM morpholog.claims
    WHERE predicate_name = 'MayCaptureTrade'
)
SELECT
    asserted_in                AS "_morpholog_asserted_in",
    asserted_at                AS "_morpholog_asserted_at",
    arguments                  AS "_morpholog_arguments",
    arguments -> 0 ->> 'value' AS "actor",
    arguments -> 1 ->> 'value' AS "org",
    arguments -> 2 ->> 'value' AS "book"
FROM governed_claims;
COMMENT ON VIEW "morpholog_views"."may_capture_trade" IS 'Generated by Morpholog; predicate=MayCaptureTrade';
COMMENT ON COLUMN "morpholog_views"."may_capture_trade"."actor" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."may_capture_trade"."org" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."may_capture_trade"."book" IS 'Morpholog kind Subject';

-- View for base predicate `MayRegisterCurve`.
CREATE OR REPLACE VIEW "morpholog_views"."may_register_curve" AS
WITH governed_claims AS (
    SELECT arguments, asserted_in, asserted_at
    FROM morpholog.claims
    WHERE predicate_name = 'MayRegisterCurve'
)
SELECT
    asserted_in                AS "_morpholog_asserted_in",
    asserted_at                AS "_morpholog_asserted_at",
    arguments                  AS "_morpholog_arguments",
    arguments -> 0 ->> 'value' AS "actor",
    arguments -> 1 ->> 'value' AS "org",
    arguments -> 2 ->> 'value' AS "market"
FROM governed_claims;
COMMENT ON VIEW "morpholog_views"."may_register_curve" IS 'Generated by Morpholog; predicate=MayRegisterCurve';
COMMENT ON COLUMN "morpholog_views"."may_register_curve"."actor" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."may_register_curve"."org" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."may_register_curve"."market" IS 'Morpholog kind Subject';

-- View for base predicate `MayValueTrade`.
CREATE OR REPLACE VIEW "morpholog_views"."may_value_trade" AS
WITH governed_claims AS (
    SELECT arguments, asserted_in, asserted_at
    FROM morpholog.claims
    WHERE predicate_name = 'MayValueTrade'
)
SELECT
    asserted_in                AS "_morpholog_asserted_in",
    asserted_at                AS "_morpholog_asserted_at",
    arguments                  AS "_morpholog_arguments",
    arguments -> 0 ->> 'value' AS "actor",
    arguments -> 1 ->> 'value' AS "org",
    arguments -> 2 ->> 'value' AS "book"
FROM governed_claims;
COMMENT ON VIEW "morpholog_views"."may_value_trade" IS 'Generated by Morpholog; predicate=MayValueTrade';
COMMENT ON COLUMN "morpholog_views"."may_value_trade"."actor" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."may_value_trade"."org" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."may_value_trade"."book" IS 'Morpholog kind Subject';

-- View for base predicate `TradeCaptured`.
CREATE OR REPLACE VIEW "morpholog_views"."trade_captured" AS
WITH governed_claims AS (
    SELECT arguments, asserted_in, asserted_at
    FROM morpholog.claims
    WHERE predicate_name = 'TradeCaptured'
)
SELECT
    asserted_in                AS "_morpholog_asserted_in",
    asserted_at                AS "_morpholog_asserted_at",
    arguments                  AS "_morpholog_arguments",
    arguments -> 0 ->> 'value' AS "org",
    arguments -> 1 ->> 'value' AS "book",
    arguments -> 2 ->> 'value' AS "trade",
    arguments -> 3 ->> 'value' AS "counterparty",
    arguments -> 4 ->> 'value' AS "market",
    arguments -> 5 ->> 'value' AS "direction"
FROM governed_claims;
COMMENT ON VIEW "morpholog_views"."trade_captured" IS 'Generated by Morpholog; predicate=TradeCaptured';
COMMENT ON COLUMN "morpholog_views"."trade_captured"."org" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."trade_captured"."book" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."trade_captured"."trade" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."trade_captured"."counterparty" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."trade_captured"."market" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."trade_captured"."direction" IS 'Morpholog kind Subject';

-- View for base predicate `TradeTerms`.
CREATE OR REPLACE VIEW "morpholog_views"."trade_terms" AS
WITH governed_claims AS (
    SELECT arguments, asserted_in, asserted_at
    FROM morpholog.claims
    WHERE predicate_name = 'TradeTerms'
)
SELECT
    asserted_in                                       AS "_morpholog_asserted_in",
    asserted_at                                       AS "_morpholog_asserted_at",
    arguments                                         AS "_morpholog_arguments",
    arguments -> 0 ->> 'value'                        AS "org",
    arguments -> 1 ->> 'value'                        AS "trade",
    (arguments -> 2 -> 'value' ->> 'amount')::numeric AS "quantity",
    (arguments -> 3 ->> 'value')::numeric             AS "price",
    (arguments -> 4 ->> 'value')::timestamptz         AS "delivery_start",
    (arguments -> 5 ->> 'value')::timestamptz         AS "delivery_end"
FROM governed_claims;
COMMENT ON VIEW "morpholog_views"."trade_terms" IS 'Generated by Morpholog; predicate=TradeTerms';
COMMENT ON COLUMN "morpholog_views"."trade_terms"."org" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."trade_terms"."trade" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."trade_terms"."quantity" IS 'Morpholog kind Decimal[MW]; amount in MW';
COMMENT ON COLUMN "morpholog_views"."trade_terms"."price" IS 'Morpholog kind Decimal';
COMMENT ON COLUMN "morpholog_views"."trade_terms"."delivery_start" IS 'Morpholog kind Timestamp; PostgreSQL microsecond precision (exact source in _morpholog_arguments)';
COMMENT ON COLUMN "morpholog_views"."trade_terms"."delivery_end" IS 'Morpholog kind Timestamp; PostgreSQL microsecond precision (exact source in _morpholog_arguments)';

-- View for base predicate `CurveRegistered`.
CREATE OR REPLACE VIEW "morpholog_views"."curve_registered" AS
WITH governed_claims AS (
    SELECT arguments, asserted_in, asserted_at
    FROM morpholog.claims
    WHERE predicate_name = 'CurveRegistered'
)
SELECT
    asserted_in                        AS "_morpholog_asserted_in",
    asserted_at                        AS "_morpholog_asserted_at",
    arguments                          AS "_morpholog_arguments",
    arguments -> 0 ->> 'value'         AS "org",
    arguments -> 1 ->> 'value'         AS "market",
    (arguments -> 2 ->> 'value')::date AS "as_of",
    arguments -> 3 ->> 'value'         AS "version",
    arguments -> 4 ->> 'value'         AS "payload_hash"
FROM governed_claims;
COMMENT ON VIEW "morpholog_views"."curve_registered" IS 'Generated by Morpholog; predicate=CurveRegistered';
COMMENT ON COLUMN "morpholog_views"."curve_registered"."org" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."curve_registered"."market" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."curve_registered"."as_of" IS 'Morpholog kind Date';
COMMENT ON COLUMN "morpholog_views"."curve_registered"."version" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."curve_registered"."payload_hash" IS 'Morpholog kind Subject';

-- View for base predicate `OfficialCurve`.
CREATE OR REPLACE VIEW "morpholog_views"."official_curve" AS
WITH governed_claims AS (
    SELECT arguments, asserted_in, asserted_at
    FROM morpholog.claims
    WHERE predicate_name = 'OfficialCurve'
)
SELECT
    asserted_in                        AS "_morpholog_asserted_in",
    asserted_at                        AS "_morpholog_asserted_at",
    arguments                          AS "_morpholog_arguments",
    arguments -> 0 ->> 'value'         AS "org",
    arguments -> 1 ->> 'value'         AS "market",
    (arguments -> 2 ->> 'value')::date AS "as_of",
    arguments -> 3 ->> 'value'         AS "version"
FROM governed_claims;
COMMENT ON VIEW "morpholog_views"."official_curve" IS 'Generated by Morpholog; predicate=OfficialCurve';
COMMENT ON COLUMN "morpholog_views"."official_curve"."org" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."official_curve"."market" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."official_curve"."as_of" IS 'Morpholog kind Date';
COMMENT ON COLUMN "morpholog_views"."official_curve"."version" IS 'Morpholog kind Subject';

-- View for base predicate `CurveSupersedes`.
CREATE OR REPLACE VIEW "morpholog_views"."curve_supersedes" AS
WITH governed_claims AS (
    SELECT arguments, asserted_in, asserted_at
    FROM morpholog.claims
    WHERE predicate_name = 'CurveSupersedes'
)
SELECT
    asserted_in                AS "_morpholog_asserted_in",
    asserted_at                AS "_morpholog_asserted_at",
    arguments                  AS "_morpholog_arguments",
    arguments -> 0 ->> 'value' AS "new_version",
    arguments -> 1 ->> 'value' AS "prior_version"
FROM governed_claims;
COMMENT ON VIEW "morpholog_views"."curve_supersedes" IS 'Generated by Morpholog; predicate=CurveSupersedes';
COMMENT ON COLUMN "morpholog_views"."curve_supersedes"."new_version" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."curve_supersedes"."prior_version" IS 'Morpholog kind Subject';

-- View for base predicate `TradeValued`.
CREATE OR REPLACE VIEW "morpholog_views"."trade_valued" AS
WITH governed_claims AS (
    SELECT arguments, asserted_in, asserted_at
    FROM morpholog.claims
    WHERE predicate_name = 'TradeValued'
)
SELECT
    asserted_in                                       AS "_morpholog_asserted_in",
    asserted_at                                       AS "_morpholog_asserted_at",
    arguments                                         AS "_morpholog_arguments",
    arguments -> 0 ->> 'value'                        AS "org",
    arguments -> 1 ->> 'value'                        AS "book",
    arguments -> 2 ->> 'value'                        AS "trade",
    arguments -> 3 ->> 'value'                        AS "curve_version",
    (arguments -> 4 -> 'value' ->> 'amount')::numeric AS "mtm"
FROM governed_claims;
COMMENT ON VIEW "morpholog_views"."trade_valued" IS 'Generated by Morpholog; predicate=TradeValued';
COMMENT ON COLUMN "morpholog_views"."trade_valued"."org" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."trade_valued"."book" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."trade_valued"."trade" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."trade_valued"."curve_version" IS 'Morpholog kind Subject';
COMMENT ON COLUMN "morpholog_views"."trade_valued"."mtm" IS 'Morpholog kind Decimal[EUR]; amount in EUR';

-- Model catalogue: the programme, its model hash, and the views generated.
CREATE OR REPLACE VIEW "morpholog_views"."_morpholog_catalog" AS
SELECT * FROM ( VALUES
    ('glasshouse'::text, 'sha256:7045468e03712a8bdaf66e6f2d43337bbf9b88c0803c6bbb34f597735fcc3897'::text, 'MayCaptureTrade'::text, 'may_capture_trade'::text, 'base'::text),
    ('glasshouse', 'sha256:7045468e03712a8bdaf66e6f2d43337bbf9b88c0803c6bbb34f597735fcc3897', 'MayRegisterCurve', 'may_register_curve', 'base'),
    ('glasshouse', 'sha256:7045468e03712a8bdaf66e6f2d43337bbf9b88c0803c6bbb34f597735fcc3897', 'MayValueTrade', 'may_value_trade', 'base'),
    ('glasshouse', 'sha256:7045468e03712a8bdaf66e6f2d43337bbf9b88c0803c6bbb34f597735fcc3897', 'TradeCaptured', 'trade_captured', 'base'),
    ('glasshouse', 'sha256:7045468e03712a8bdaf66e6f2d43337bbf9b88c0803c6bbb34f597735fcc3897', 'TradeTerms', 'trade_terms', 'base'),
    ('glasshouse', 'sha256:7045468e03712a8bdaf66e6f2d43337bbf9b88c0803c6bbb34f597735fcc3897', 'CurveRegistered', 'curve_registered', 'base'),
    ('glasshouse', 'sha256:7045468e03712a8bdaf66e6f2d43337bbf9b88c0803c6bbb34f597735fcc3897', 'OfficialCurve', 'official_curve', 'base'),
    ('glasshouse', 'sha256:7045468e03712a8bdaf66e6f2d43337bbf9b88c0803c6bbb34f597735fcc3897', 'CurveSupersedes', 'curve_supersedes', 'base'),
    ('glasshouse', 'sha256:7045468e03712a8bdaf66e6f2d43337bbf9b88c0803c6bbb34f597735fcc3897', 'TradeValued', 'trade_valued', 'base')
) AS generated(programme_name, model_hash, predicate_name, view_name, kind);
COMMENT ON VIEW "morpholog_views"."_morpholog_catalog" IS 'Generated by Morpholog; the model catalogue for this view surface';

COMMIT;
