"""A typed Morpholog client for programme `glasshouse`.

GENERATED by `morpholog generate python-client` - do not edit;
regenerate when the programme changes. The model hash in
`__init__.py` names the rules this client was built against.
"""

import sys

if sys.version_info < (3, 10):
    raise RuntimeError(
        f"morpholog_client requires Python 3.10+ "
        f"(running {sys.version_info.major}.{sys.version_info.minor}); "
        f"the generated code holds a conservative floor on purpose"
    )

PROGRAM = "glasshouse"
MODEL_HASH = "sha256:7045468e03712a8bdaf66e6f2d43337bbf9b88c0803c6bbb34f597735fcc3897"
MORPHOLOG_VERSION = "0.0.1"
PYTHON_FLOOR = (3, 10)

from . import envelopes, models, values  # noqa: E402
from .adapter import Morpholog, MorphologError  # noqa: E402

__all__ = [
    "PROGRAM",
    "MODEL_HASH",
    "MORPHOLOG_VERSION",
    "PYTHON_FLOOR",
    "Morpholog",
    "MorphologError",
    "envelopes",
    "models",
    "values",
]
