"""Typed request, read, and payload models for programme `glasshouse`.

GENERATED by `morpholog generate python-client` - do not edit;
regenerate when the programme changes. The model hash in
`__init__.py` names the rules this client was built against.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date, datetime
from decimal import Decimal
from typing import ClassVar

from . import values


@dataclass(frozen=True)
class GrantCaptureAuthorityRequest:
    """Arguments for `grant_capture_authority`."""

    TRANSFORMATION: ClassVar[str] = "grant_capture_authority"

    principal: str
    org: str
    book: str

    def to_args_named(self) -> dict:
        return {
            "principal": values.encode_named(self.principal),
            "org": values.encode_named(self.org),
            "book": values.encode_named(self.book),
        }


@dataclass(frozen=True)
class GrantCurveAuthorityRequest:
    """Arguments for `grant_curve_authority`."""

    TRANSFORMATION: ClassVar[str] = "grant_curve_authority"

    principal: str
    org: str
    market: str

    def to_args_named(self) -> dict:
        return {
            "principal": values.encode_named(self.principal),
            "org": values.encode_named(self.org),
            "market": values.encode_named(self.market),
        }


@dataclass(frozen=True)
class GrantValuationAuthorityRequest:
    """Arguments for `grant_valuation_authority`."""

    TRANSFORMATION: ClassVar[str] = "grant_valuation_authority"

    principal: str
    org: str
    book: str

    def to_args_named(self) -> dict:
        return {
            "principal": values.encode_named(self.principal),
            "org": values.encode_named(self.org),
            "book": values.encode_named(self.book),
        }


@dataclass(frozen=True)
class CaptureTradeRequest:
    """Arguments for `capture_trade`."""

    TRANSFORMATION: ClassVar[str] = "capture_trade"

    org: str
    book: str
    trade: str
    counterparty: str
    market: str
    direction: str
    quantity: Decimal
    # amount in MW (the declaration carries the unit)
    price: Decimal
    delivery_start: datetime
    delivery_end: datetime

    def to_args_named(self) -> dict:
        return {
            "org": values.encode_named(self.org),
            "book": values.encode_named(self.book),
            "trade": values.encode_named(self.trade),
            "counterparty": values.encode_named(self.counterparty),
            "market": values.encode_named(self.market),
            "direction": values.encode_named(self.direction),
            "quantity": values.encode_named(self.quantity),
            "price": values.encode_named(self.price),
            "delivery_start": values.encode_named(self.delivery_start),
            "delivery_end": values.encode_named(self.delivery_end),
        }


@dataclass(frozen=True)
class RegisterCurveRequest:
    """Arguments for `register_curve`."""

    TRANSFORMATION: ClassVar[str] = "register_curve"

    org: str
    market: str
    as_of: date
    version: str
    payload_hash: str

    def to_args_named(self) -> dict:
        return {
            "org": values.encode_named(self.org),
            "market": values.encode_named(self.market),
            "as_of": values.encode_named(self.as_of),
            "version": values.encode_named(self.version),
            "payload_hash": values.encode_named(self.payload_hash),
        }


@dataclass(frozen=True)
class CorrectCurveRequest:
    """Arguments for `correct_curve`."""

    TRANSFORMATION: ClassVar[str] = "correct_curve"

    org: str
    market: str
    as_of: date
    prior_version: str
    new_version: str
    payload_hash: str

    def to_args_named(self) -> dict:
        return {
            "org": values.encode_named(self.org),
            "market": values.encode_named(self.market),
            "as_of": values.encode_named(self.as_of),
            "prior_version": values.encode_named(self.prior_version),
            "new_version": values.encode_named(self.new_version),
            "payload_hash": values.encode_named(self.payload_hash),
        }


@dataclass(frozen=True)
class AdmitValuationRequest:
    """Arguments for `admit_valuation`."""

    TRANSFORMATION: ClassVar[str] = "admit_valuation"

    org: str
    book: str
    trade: str
    curve_version: str
    mtm: Decimal
    # amount in EUR (the declaration carries the unit)

    def to_args_named(self) -> dict:
        return {
            "org": values.encode_named(self.org),
            "book": values.encode_named(self.book),
            "trade": values.encode_named(self.trade),
            "curve_version": values.encode_named(self.curve_version),
            "mtm": values.encode_named(self.mtm),
        }


@dataclass(frozen=True)
class MayCaptureTradeClaim:
    """One admitted `MayCaptureTrade` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "MayCaptureTrade"

    actor: str
    org: str
    book: str

    @classmethod
    def from_named(cls, args: dict) -> "MayCaptureTradeClaim":
        raw = args["actor"]
        actor = raw
        raw = args["org"]
        org = raw
        raw = args["book"]
        book = raw
        return cls(actor=actor, org=org, book=book)


@dataclass(frozen=True)
class MayRegisterCurveClaim:
    """One admitted `MayRegisterCurve` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "MayRegisterCurve"

    actor: str
    org: str
    market: str

    @classmethod
    def from_named(cls, args: dict) -> "MayRegisterCurveClaim":
        raw = args["actor"]
        actor = raw
        raw = args["org"]
        org = raw
        raw = args["market"]
        market = raw
        return cls(actor=actor, org=org, market=market)


@dataclass(frozen=True)
class MayValueTradeClaim:
    """One admitted `MayValueTrade` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "MayValueTrade"

    actor: str
    org: str
    book: str

    @classmethod
    def from_named(cls, args: dict) -> "MayValueTradeClaim":
        raw = args["actor"]
        actor = raw
        raw = args["org"]
        org = raw
        raw = args["book"]
        book = raw
        return cls(actor=actor, org=org, book=book)


@dataclass(frozen=True)
class TradeCapturedClaim:
    """One admitted `TradeCaptured` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "TradeCaptured"

    org: str
    book: str
    trade: str
    counterparty: str
    market: str
    direction: str

    @classmethod
    def from_named(cls, args: dict) -> "TradeCapturedClaim":
        raw = args["org"]
        org = raw
        raw = args["book"]
        book = raw
        raw = args["trade"]
        trade = raw
        raw = args["counterparty"]
        counterparty = raw
        raw = args["market"]
        market = raw
        raw = args["direction"]
        direction = raw
        return cls(org=org, book=book, trade=trade, counterparty=counterparty, market=market, direction=direction)


@dataclass(frozen=True)
class TradeTermsClaim:
    """One admitted `TradeTerms` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "TradeTerms"

    org: str
    trade: str
    quantity: Decimal
    # amount in MW (the declaration carries the unit)
    price: Decimal
    delivery_start: datetime
    delivery_end: datetime

    @classmethod
    def from_named(cls, args: dict) -> "TradeTermsClaim":
        raw = args["org"]
        org = raw
        raw = args["trade"]
        trade = raw
        raw = args["quantity"]
        quantity = values.parse_decimal(raw)
        raw = args["price"]
        price = values.parse_decimal(raw)
        raw = args["delivery_start"]
        delivery_start = values.parse_timestamp(raw)
        raw = args["delivery_end"]
        delivery_end = values.parse_timestamp(raw)
        return cls(org=org, trade=trade, quantity=quantity, price=price, delivery_start=delivery_start, delivery_end=delivery_end)


@dataclass(frozen=True)
class CurveRegisteredClaim:
    """One admitted `CurveRegistered` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "CurveRegistered"

    org: str
    market: str
    as_of: date
    version: str
    payload_hash: str

    @classmethod
    def from_named(cls, args: dict) -> "CurveRegisteredClaim":
        raw = args["org"]
        org = raw
        raw = args["market"]
        market = raw
        raw = args["as_of"]
        as_of = values.parse_date(raw)
        raw = args["version"]
        version = raw
        raw = args["payload_hash"]
        payload_hash = raw
        return cls(org=org, market=market, as_of=as_of, version=version, payload_hash=payload_hash)


@dataclass(frozen=True)
class OfficialCurveClaim:
    """One admitted `OfficialCurve` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "OfficialCurve"

    org: str
    market: str
    as_of: date
    version: str

    @classmethod
    def from_named(cls, args: dict) -> "OfficialCurveClaim":
        raw = args["org"]
        org = raw
        raw = args["market"]
        market = raw
        raw = args["as_of"]
        as_of = values.parse_date(raw)
        raw = args["version"]
        version = raw
        return cls(org=org, market=market, as_of=as_of, version=version)


@dataclass(frozen=True)
class CurveSupersedesClaim:
    """One admitted `CurveSupersedes` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "CurveSupersedes"

    new_version: str
    prior_version: str

    @classmethod
    def from_named(cls, args: dict) -> "CurveSupersedesClaim":
        raw = args["new_version"]
        new_version = raw
        raw = args["prior_version"]
        prior_version = raw
        return cls(new_version=new_version, prior_version=prior_version)


@dataclass(frozen=True)
class TradeValuedClaim:
    """One admitted `TradeValued` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "TradeValued"

    org: str
    book: str
    trade: str
    curve_version: str
    mtm: Decimal
    # amount in EUR (the declaration carries the unit)

    @classmethod
    def from_named(cls, args: dict) -> "TradeValuedClaim":
        raw = args["org"]
        org = raw
        raw = args["book"]
        book = raw
        raw = args["trade"]
        trade = raw
        raw = args["curve_version"]
        curve_version = raw
        raw = args["mtm"]
        mtm = values.parse_decimal(raw)
        return cls(org=org, book=book, trade=trade, curve_version=curve_version, mtm=mtm)


INTENT_PAYLOADS = {

}
